#!/bin/sh

set -e

if [ $# -eq 0 ]; then
    echo "Usage: $0 packagelist.txt"
    exit 2
fi

echo "Generating installed package list"
dpkg -l | dpkg --get-selections | grep installed 1> "$0"
