#!/bin/sh

set -e

class="$1"
target="$2"

if [ $# -ne 1 ]; then
    echo "Usage: $0 class target"
    exit 2
fi

echo "Apply customization using FAI copy"
fcopy -BMri -v -s files/ -t "$target" -c "$class" /
